version: '3'

services:
  prayeralarm:
    build:
      context: ./
    # image: zeeshans/prayeralarm:latest
    container_name: prayeralarm
    platform: linux/arm/v7
    restart: unless-stopped
    devices:
      - /dev/snd:/dev/snd
      - /dev/vchiq:/dev/vchiq
    ports:
      - 8080:8080
