// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

package main

import "time"

type MonthlyAdhanCalenderResponse struct {
	Code   int64  `json:"code"`
	Status string `json:"status"`
	Data   []struct {
		Timings map[Adhan]string `json:"timings"`
		Date    struct {
			Readable  string `json:"readable"`
			Timestamp string `json:"timestamp"`
		} `json:"date"`
		Meta struct {
			Latitude  float64               `json:"latitude"`
			Longitude float64               `json:"longitude"`
			Timezone  string                `json:"timezone"`
			Offset    map[Adhan]interface{} `json:"offset"` // string or int
		} `json:"meta"`
	} `json:"data"`
}

type Timing struct {
	Fajr    string
	Dhuhr   string
	Asr     string
	Maghrib string
	Isha    string
}

type Adhan string

const (
	Fajr    Adhan = "Fajr"
	Dhuhr   Adhan = "Dhuhr"
	Asr     Adhan = "Asr"
	Maghrib Adhan = "Maghrib"
	Isha    Adhan = "Isha"
)

type AdhanTime struct {
	Type Adhan
	Time time.Time
}
