name: CD

on:
  push:
    branches: [ master ]

jobs:
  upload_binary_artifact:
    name: Create RPi release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: Install sound dependencies
        run: sudo apt-get install -y libasound2-dev
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cross-compile for raspberry pi
        run: CC=arm-linux-gnueabihf-gcc GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=1 go build -v .
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: prayeralarm-artifact
          path: ./prayeralarm

  deploy_binary:
    name: Raspberry PI Deployment
    needs: upload_binary_artifact
    runs-on: [self-hosted]
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: prayeralarm-artifact
          path: ./prayeralarm
