name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Raspberry PI Deployment
    runs-on: [self-hosted, golang]
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: Install sound dependencies
        run: sudo apt-get install libasound2-dev
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build for raspberry pi
        run: GOOS=linux GOARCH=arm GOARM=5 CGO_ENABLED=1 go build -v .
      - name: Deploy binary with static files
        run: ls -la /tmp
