name: CD

on:
  push:
    branches: [ master ]

jobs:
  deploy_self_hosted:
    name: Deploy to self-hosted (raspberry pi)
    runs-on: [self-hosted]
    strategy:
      matrix:
        go-version: [1.15.x]
    steps:
      - name: Install sound dependencies
        run: sudo apt-get install -y libasound2-dev
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile for machine
        run: CGO_ENABLED=1 go build -v .
      - name: Test
        run: ls -la  /tmp
