name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        go-version: [1.15.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    # - name: Run vet & lint
    #   run: |
    #     CGO_ENABLED=1 go vet .
    #     CGO_ENABLED=1 golint .
    - name: Test
      run: CGO_ENABLED=1 go test .
    - name: Build
      run: CGO_ENABLED=1 go build -v .
